spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/db_tcc'
    username: root
    password: liroot1287
    testeWhileIdle: 'true'
    validationQuery: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: "true"
    hibernate:
      ddl-auto: "create"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"

logging:
    level:
      org:
        hibernate:
          SQL: "DEBUG"
          type:
            descriptor:
              sql:
                BasicBinder: "TRACE"

jwt:
  token:
    validity: 7200
    prefix: "Bearer "
  signing:
    key: "poucasideias"
  authorities:
    key: "roles"
  header:
    string: "Authorization"
