spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/interfriends"
    username: "root"
    testeWhileIdle: "true"
    validationQuery: "SELECT 1"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    show-sql: "true"
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

logging:
    level:
      org:
        hibernate:
          SQL: "DEBUG"
          type:
            descriptor:
              sql:
                BasicBinder: "TRACE"

jwt:
  token:
    validity: 18000
    prefix: "Bearer "
  signing:
    key: "poucasideias"
  authorities:
    key: "roles"
  header:
    string: "Authorization"
